version: '3.8'

services:
  pg:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: master
    volumes:
      - pg:/data/db
volumes:
  pg:
